package email

const (
	ENVKEY_SMTP_HOST = "SMTP_HOST"
	ENVKEY_SMTP_PORT = "SMTP_PORT"
	ENVKEY_SMTP_USER = "SMTP_USER"
	ENVKEY_SMTP_PASS = "SMTP_PASSWORD"
	ENVKEY_SMTP_FROM = "SMTP_FROM"
)

const (
	DEFAULT_SMTP_PORT = 587
)
