package config

const (
	ENVKEY_DBUSER   = "MYSQL_USER"
	ENVKEY_DBPW     = "MYSQL_PASSWORD"
	ENVKEY_DBROOTPW = "MYSQL_ROOT_PASSWORD"
	ENVKEY_DBNAME   = "MYSQL_DATABASE"
	ENVKEY_DBHOST   = "MYSQL_HOST"
	ENVKEY_DBPORT   = "MYSQL_PORT"
)

const (
	ENVKEY_ADMIN_EMAIL = "ADMIN_EMAIL"
	ENVKEY_ADMIN_FNAME = "ADMIN_FIRST_NAME"
	ENVKEY_ADMIN_LNAME = "ADMIN_LAST_NAME"
)

const (
	FRONTEND_BASE_URL = "FRONTEND_BASE_URL"
)
